plugins {
    id 'java'
    id 'application'
    id 'edu.sc.seis.launch4j' version '4.0.0'
    id 'edu.sc.seis.macAppBundle' version '2.3.1'
}

configurations.named("default") {
    canBeResolved = true
}

launch4j {
    mainClassName = 'me.blackout.claustrum.Main'
    headerType = 'gui'
    outfile = 'Claustrum.exe'
    icon = "${projectDir}/src/main/resources/Claustrum.ico"
}

macAppBundle {
    appName = "Claustrum"
    mainClassName = "me.blackout.claustrum.Main"
    icon = "icons/Claustrum.icns"
}

group 'blackout'

repositories {
    mavenCentral()
}

dependencies {
}

jar {
    manifest {
        attributes("Main-Class": "me.blackout.claustrum.Main")
    }
}